backend:
  name: github
  repo: meinrehlein/jannis2

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: "src/data/projects"
    create: true
    extension: md
    slug: "{{name}}"
    sortable_fields: [commit_date, year]
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Year, name: year, widget: number }
      - { label: Month in numbers from "1" to "12", name: month, widget: number, min: 1, max: 12 }
      - { label: Location, name: location, widget: string }
      - { label: Type (DE) z.B. "Bühnenbild", name: type, widget: string, required: false }
      - { label: Type (EN) z.B. "Stagedesign", name: type_en, widget: string, required: false }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: Image, name: src, widget: image }
          - { label: Alt Text, name: alt, widget: string }
      - { label: Category, name: category, widget: select, options: [A,B,C], default: B }
      - { label: Orientation, name: orientation, widget: select, options: ['1:1.4','1.4:1'], default: '1:1.4' }
      - { label: Body (DE), name: body, widget: markdown, required: false  }
      - { label: Body (EN), name: body_en, widget: markdown, required: false }
